check if name is not empty before constructing message.
Ostorlab/agent_whois_domain pull request #27
Opened 2023-01-31 17:06 UTC by najibraihan

2023-01-31 22:55 UTC, amine3 requested changes

2023-01-31 22:55 UTC, amine3 commented on agent/result_parser.py
> +        if name != "":
Missing unit test to check the behavior if name is empty string

2023-01-31 22:56 UTC, 3asm submitted a review, later dismissed

2023-02-01 10:38 UTC, amine3 approved these changes

2023-02-01 12:03 UTC, 3asm approved these changes

2023-02-01 14:37 UTC, merged