Fix whois crash: 'str' object has no attribute extend
Ostorlab/agent_whois_domain pull request #28
Opened 2023-02-01 15:09 UTC by najibraihan

2023-02-01 15:20 UTC, mohsinenar requested changes

2023-02-01 15:20 UTC, mohsinenar commented on agent/result_parser.py
> +                "name": _format_str(name) if name is not None else name,
The fix should be in `_format_str` to just return None if the value is None, otherwise, the code will fail, if anywhere else we have the same issue.

2023-02-01 17:54 UTC, 3asm requested changes

2023-02-01 17:54 UTC, 3asm commented on agent/result_parser.py
> +                "contact_name": contact_name[0]
This needs a dedicated unit test, not changing the existing ones.

2023-02-02 21:39 UTC, 3asm submitted a review, later dismissed

2023-02-02 21:39 UTC, 3asm commented on tests/whois_domain_agent_test.py
> +def testAgentWhois_whenDomainNameISEmpty_NotEmitsMessages(
```suggestion
def testAgentWhois_whenDomainNameIsEmpty_notEmitsMessages(
```

2023-02-02 21:39 UTC, 3asm commented on tests/whois_domain_agent_test.py
> +    assert agent_mock[0].selector == "v3.asset.domain_name.whois"
```suggestion
    test_agent.process(scan_message)
    mock_whois.assert_called_once()
    
    assert len(agent_mock) > 0
    assert agent_mock[0].selector == "v3.asset.domain_name.whois"
```

2023-02-03 11:54 UTC, 3asm approved these changes

2023-02-03 14:36 UTC, merged